### ISSUE TITLE
Anilist API

### ISSUE THREAD

**Issue by toprak** [rl404/inazuma#95]
Myanimelist's manga database is very weak compared to Anilist, it might be better to switch to Anilist API

**Comment by rl404** [comment]
I couldn't agree more to that. I am aware that Myanimelist API is worse than Anilist APi in general. But yeah my inazuma & hibiki project are just for fun. I don't have time and motivation to switch to Anilist API. Even if I have them, I prefer creating new project rather than updating the existing ones.

Thanks for the suggestion.
